"use client";

import type { ReactNode } from "react";
import { ArrowLeft, Copy, MapPin, Package, Truck } from "lucide-react";
import { FULFILLMENT_STATUSES, money, shortDate, STATUS_CLASS, STATUS_LABEL } from "../config";
import { WarehouseOrder, OrderStatus } from "../types/order";

export function OrderDetails({ order, onBack, onStatusChange }: { order: WarehouseOrder; onBack: () => void; onStatusChange: (id: string, status: OrderStatus) => Promise<void> | void }) {
  return <div className="mx-auto max-w-6xl space-y-5"><button onClick={onBack} className="flex items-center gap-2 text-sm font-bold text-slate-600 hover:text-blue-600"><ArrowLeft size={16} /> Back to orders</button>
    <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><div className="flex items-center gap-2"><h1 className="text-xl font-black text-slate-950">Order {order.orderId}</h1><button onClick={() => navigator.clipboard.writeText(order.orderId)} className="text-slate-400 hover:text-blue-600"><Copy size={15} /></button></div><p className="mt-1 text-xs text-slate-500">Placed {shortDate(order.createdAt)} by {order.customer}</p></div><select value={order.status} onChange={(e) => onStatusChange(order.id, e.target.value as OrderStatus)} className={`rounded-xl border px-4 py-2 text-xs font-bold ${STATUS_CLASS[order.status]}`}>{FULFILLMENT_STATUSES.map((status) => <option value={status} key={status}>{STATUS_LABEL[status]}</option>)}</select></div></section>
    <div className="grid gap-5 lg:grid-cols-[1.4fr_.6fr]"><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="mb-4 flex items-center gap-2 font-bold text-slate-900"><Package size={17} className="text-blue-600" /> Products</h2><div className="divide-y divide-slate-100">{order.items.map((item) => <div key={item.id} className="flex items-center justify-between py-4"><div className="flex items-center gap-3">{item.image ? <img src={item.image} alt="" className="h-12 w-12 rounded-xl border object-cover" /> : <div className="h-12 w-12 rounded-xl bg-slate-100" />}<div><p className="text-sm font-bold text-slate-800">{item.name}</p><p className="text-xs text-slate-500">Qty {item.quantity}</p></div></div><p className="font-bold text-slate-900">{money(item.price * item.quantity)}</p></div>)}</div></section><aside className="space-y-5"><Info title="Shipping" icon={Truck}><p>{order.shippingMethod ?? "Standard shipping"}</p><p>{order.courier ?? "Courier not assigned"}</p><p>{order.trackingNumber ?? "Tracking pending"}</p></Info><Info title="Delivery address" icon={MapPin}><p>{order.shippingAddress ?? "Address unavailable"}</p><p>{order.phone}</p></Info><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-4 font-bold text-slate-900">Payment summary</h2><Line label="Subtotal" value={money(order.subtotal)} /><Line label="Taxes" value={money(order.taxes)} /><Line label="Shipping" value={money(order.shipping)} /><Line label="Discount" value={`-${money(order.discount)}`} /><div className="mt-3 border-t pt-3"><Line label="Grand total" value={money(order.total)} strong /></div></section></aside></div>
  </div>;
}
function Info({ title, icon: Icon, children }: { title: string; icon: typeof Truck; children: ReactNode }) { return <section className="rounded-2xl border border-slate-200 bg-white p-5 text-sm text-slate-600 shadow-sm"><h2 className="mb-3 flex items-center gap-2 font-bold text-slate-900"><Icon size={16} className="text-blue-600" />{title}</h2><div className="space-y-1">{children}</div></section>; }
function Line({ label, value, strong }: { label: string; value: string; strong?: boolean }) { return <div className={`flex justify-between py-1.5 text-sm ${strong ? "font-black text-slate-950" : "text-slate-600"}`}><span>{label}</span><span>{value}</span></div>; }