"use client";

import { useMemo, useState } from "react";
import { ChevronRight, MoreHorizontal, Search } from "lucide-react";
import { FULFILLMENT_STATUSES, money, shortDate, STATUS_CLASS, STATUS_LABEL } from "../config";
import type { OrderStatus, WarehouseOrder } from "../types/order";

interface Props { orders: WarehouseOrder[]; onOpen: (order: WarehouseOrder) => void; onStatusChange: (id: string, status: OrderStatus) => Promise<void> | void; }

export function OrdersWorkspace({ orders, onOpen, onStatusChange }: Props) {
  const [query, setQuery] = useState(""); const [status, setStatus] = useState<OrderStatus | "all">("all"); const [selected, setSelected] = useState<string[]>([]);
  const rows = useMemo(() => orders.filter((o) => (status === "all" || o.status === status) && `${o.orderId} ${o.customer} ${o.items.map((i) => i.name)}`.toLowerCase().includes(query.toLowerCase())), [orders, query, status]);
  const toggleAll = () => setSelected(selected.length === rows.length ? [] : rows.map((o) => o.id));
  const bulkUpdate = async (next: OrderStatus) => { await Promise.all(selected.map((id) => onStatusChange(id, next))); setSelected([]); };
  return <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
    <div className="flex flex-col gap-3 border-b border-slate-100 p-5 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="font-bold text-slate-900">All orders</h2><p className="text-xs text-slate-500">Search, review and update fulfillment without leaving the table.</p></div><div className="flex flex-wrap gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-2.5 text-slate-400" size={15} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search orders..." className="min-w-52 rounded-xl border border-slate-200 py-2 pl-9 pr-3 text-xs outline-none focus:border-blue-500" /></div><select value={status} onChange={(e) => setStatus(e.target.value as OrderStatus | "all")} className="rounded-xl border border-slate-200 px-3 text-xs font-semibold"><option value="all">All statuses</option>{FULFILLMENT_STATUSES.map((item) => <option key={item} value={item}>{STATUS_LABEL[item]}</option>)}</select></div></div>
    {selected.length > 0 && <div className="flex items-center gap-3 bg-blue-50 px-5 py-3 text-xs"><b className="text-blue-700">{selected.length} selected</b><span className="text-blue-300">|</span><span className="font-medium text-blue-700">Move to</span>{["processing", "packed", "shipped", "cancelled"].map((item) => <button key={item} onClick={() => bulkUpdate(item as OrderStatus)} className="rounded-lg bg-white px-3 py-1.5 font-bold text-slate-700 shadow-sm hover:text-blue-600">{STATUS_LABEL[item as OrderStatus]}</button>)}</div>}
    <div className="max-h-[680px] overflow-auto"><table className="w-full min-w-[1050px] text-left"><thead className="sticky top-0 z-10 bg-slate-50"><tr className="text-[11px] uppercase tracking-wide text-slate-500"><th className="px-5 py-3"><input type="checkbox" checked={rows.length > 0 && selected.length === rows.length} onChange={toggleAll} /></th>{["Order ID", "Customer", "Product", "Status", "Payment", "Date", "Amount", "Actions"].map((h) => <th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map((order) => <tr key={order.id} className="group hover:bg-blue-50/30"><td className="px-5 py-4"><input type="checkbox" checked={selected.includes(order.id)} onChange={() => setSelected((all) => all.includes(order.id) ? all.filter((id) => id !== order.id) : [...all, order.id])} /></td><td className="px-4 py-4 font-mono text-xs font-bold text-blue-600">{order.orderId}</td><td className="px-4 py-4 text-sm font-semibold text-slate-800">{order.customer}</td><td className="max-w-56 truncate px-4 py-4 text-sm text-slate-600">{order.items[0]?.name ?? "—"}{order.items.length > 1 && ` +${order.items.length - 1}`}</td><td className="px-4 py-4"><select value={order.status} onChange={(e) => onStatusChange(order.id, e.target.value as OrderStatus)} className={`rounded-full border px-2 py-1 text-[11px] font-bold outline-none ${STATUS_CLASS[order.status]}`}>{FULFILLMENT_STATUSES.map((item) => <option key={item} value={item}>{STATUS_LABEL[item]}</option>)}</select></td><td className="px-4 py-4 text-xs font-semibold text-slate-600">{order.paymentMethod === "cod" ? "COD" : order.paymentStatus === "paid" ? "Paid online" : "Online pending"}</td><td className="px-4 py-4 text-xs text-slate-500">{shortDate(order.createdAt)}</td><td className="px-4 py-4 text-sm font-bold text-slate-900">{money(order.total)}</td><td className="px-4 py-4"><button onClick={() => onOpen(order)} title="Open order" className="rounded-lg p-2 text-slate-400 opacity-0 transition hover:bg-white hover:text-blue-600 group-hover:opacity-100"><ChevronRight size={16} /></button><button title="More actions" className="rounded-lg p-2 text-slate-400 opacity-0 group-hover:opacity-100"><MoreHorizontal size={16} /></button></td></tr>)}</tbody></table>{!rows.length && <p className="p-10 text-center text-sm text-slate-400">No orders match the current filters.</p>}</div>
  </section>;
}

export function FulfillmentKanban({ orders, onOpen, onStatusChange }: Props) {
  const columns: OrderStatus[] = ["pending", "confirmed", "packed", "shipped"];
  return <div className="grid min-w-[1000px] grid-cols-4 gap-4 overflow-x-auto pb-3">{columns.map((status) => { const list = orders.filter((o) => o.status === status); return <section key={status} onDragOver={(e) => e.preventDefault()} onDrop={(e) => onStatusChange(e.dataTransfer.getData("orderId"), status)} className="min-h-[620px] rounded-2xl border border-slate-200 bg-slate-100/70 p-3"><div className="mb-3 flex items-center justify-between px-1"><h2 className="text-sm font-bold text-slate-800">{STATUS_LABEL[status]}</h2><span className="rounded-full bg-white px-2 py-1 text-xs font-bold text-slate-500">{list.length}</span></div><div className="space-y-3">{list.map((order) => <button draggable onDragStart={(e) => e.dataTransfer.setData("orderId", order.id)} onClick={() => onOpen(order)} key={order.id} className="w-full cursor-grab rounded-xl border border-slate-200 bg-white p-4 text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-md active:cursor-grabbing"><div className="flex justify-between"><span className="font-mono text-xs font-bold text-blue-600">{order.orderId}</span><span className="text-xs font-bold text-slate-800">{money(order.total)}</span></div><p className="mt-3 text-sm font-bold text-slate-800">{order.customer}</p><p className="mt-1 truncate text-xs text-slate-500">{order.items.map((i) => `${i.quantity}× ${i.name}`).join(", ")}</p><div className="mt-3 flex justify-between text-[10px] font-semibold text-slate-400"><span>{order.priority ?? "normal"} priority</span><span>{order.shippingMethod ?? "Standard"}</span></div></button>)}</div></section>})}</div>;
}